<a href="https://colab.research.google.com/github/raflialdiansyah046-bot/Tugas_text_processing_comment_youtube/blob/main/tugas_text_processing_raditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests
import json
import pandas as pd
import re
import nltk

In [3]:
api_key = "apa_hayo_APInya"

video_id = "rR0A9xZlXqQ"
max_result = 100

url = f"https://www.googleapis.com/youtube/v3/commentThreads"

params = {
    "part": "snippet",
    "videoId": video_id,
    "maxResults": max_result,
    "key": api_key
}

response = requests.get(url, params=params)

print(response.status_code)

data = response.json()

200

In [4]:
comments = []

for item in data["items"]:
    comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
    comments.append(comment)

print("Jumlah komentar:", len(comments))

for comment in comments[:1000]:
    print(comment)

Jumlah komentar: 100
Cek, promo,
Orang kaya bilek,&quot;anjir daging premium pake nasi
Cara iris bawang nya aja masih bingung dan lama tapi lagak nya udah kayak sef tapi kalau kamu itu sef tai nya anjing
Did he just said bismillah??
sekitar 15 biji aja
nyam nyam
Kok bisa ya? Lambungnya segede apa dia teh??
lanjut mang
😮
Assalamualaikum bang ,,,coba review daging unta utuh bang ...
itu daging sapi bang?
Babah
Jujur bang, w kira daging b2 sekilas
aku nak satu
Banf makan salmon 1 ton
Makan banyak tapi yg besar hanya bibir
Kelihatanya seperti dagin Baby
Where  you  come  from ?  And what your  mission above  study ?  Thank  you  guys .
Selamat Malam Saya Yayuk  mengajukan pertanyaan , Bagaimanakah mempertahankan daging supaya  tahan lama dan aman ?<br>Saya semoga pertanyaan ini dapat di terima dan di pahami .  Terima  Kasih .
Itu daging B2 bukan sapi.. keliatan banget waktu di asapin lemak nya dan antara daging ketutup lemaknya b2itu😂
<a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=714">11:54</a>
Bang tolong bibir potong dikit
dari tahun 2021 nonton tahun pas 2026😂
Astaghfirullah ini mah bukan daging sapi tapi babi kan
wah
P
geli banget ngeliat bawang nya
DAGING BABI YA BG<br>KARENA KAYAK SAMA DAGING BABI DARI KAMPUNG SAYA <br>SOALNYA SAYA ORANG KRISTEN<br>DAN SAYA UDAH PERNA COBA
Gw k
P
Ngiler sambel nya😢
babi emang ok
gue terakhir
🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩
Enak nya bang
Close dulu
kecubunggggg
Kasih baking soda biar ijo
Boy.. kapan kapan buat konten makan daging terenak didunia yi  daging Babi.
Yang nonton 2026.?
Apkah anda Islam
Abang ini sukses bikin kita lapar
3.43 kaget jir😂😂😂
Yah gw doang yg nonton 2026
Mirip daging babi
Tak kira tadi B2<br>Sempet dikit baca judulnya
coba pork belly bang bara
SELALU
Kalo pengasapannya jelek gimana bang <a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=1074">17:54</a>
sesekali kalian makan daging babi biar tau gmn rasa daging terenak dimukanbumi yakali orang lain masa membvvnhh berani, perkaos berani, koruppppsi berani, melakukan dosal lain berani yang fi takuti cuma daging babi kan aneh,,,,
<a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=698">11:38</a>
kayak daging babi
Kota Medan hadir selalu untuk mu mas bara😅😊
Mantap bang
Bang ... Masuk idul Adha buat Tema MAKAN DAGING UNTA Donk ....
Aku kasik nonton pada orang2 miskin Dan anak2 yg sudah Dan ustaz...  Mereka senang sekali ada orang kaya Gini..
Siapa yang nonton 2026
Yang sehat ya bang
itu daging apa bg
Itu daging B2 kalau GK salah
habis lebaran 2026 ada gk yang nonton tanboy kun kalo ada 😅ya
Daging bagian bawah perut
Ini daging apa ya
<b>habis lebaran 2026 ada gk yang nonton tanboy kun ,kalo ada</b> 😅<br>👇
Jadi laper😅
nnton pas lg puasa 2026.. jam 09.51,, enak bgt liat daging asap ni😥😅😅
.
nonton ini jam 1 siang hari puasa
bang gua bisa makan nasi tanpa kunyah
Jadi pengen buka jam 1
Bang lu Islam apa katolik?
No more &#39;Don&#39;t skip—this will change your life&#39; guilt-trip ads - all thanks to Blockify
Nonton sambil nunggu buka puasa
nonton pas puasa 2026 absenn dong
info yang nonton pas otw puasa 2026😂
Yg nonton puasa 2026
hadir
2026 ada?
Yummy 😋
2026 bg
go veg-
2026🗿🗿
Itu nama dagingnya apa bang tanboy?
Itu daging babi
67!
Mati lu makan kecubung
❤❤🎉
Kerja dimana tamboy meke liliput terus lu emang enak pah itu di bau banget juga lu ..
2026
Siapa yang nonton 2026 preennn😂
Lah gw sendiri yg nonton 2026😂
gua orang pertama yg nonton di 2026.
Gua jugs bsng baru nonton ini
AMAZING!
Gak sangkut digigi😂😂😂
yang nonton 2025<br>👇
Bukannya bini nya Islam ya??
bismillah ada rejeki buat makan ini yaallaaaaah
Bagus video nya tapi ngomong nya terlalu bnyak, bagus nya makan saja, tdk usah terlalu bxk ngomong, supaya asyik di nonton
Islam kok makan babi

In [5]:
df = pd.DataFrame({
    "text": comments
})

df.head()

                                                text
0                                        Cek, promo,
1  Orang kaya bilek,&quot;anjir daging premium pa...
2  Cara iris bawang nya aja masih bingung dan lam...
3                       Did he just said bismillah??
4                                sekitar 15 biji aja

In [6]:
!pip install --upgrade git+https://github.com/ariaghora/mpstemmer.git
!pip install Levenshtein

Collecting git+https://github.com/ariaghora/mpstemmer.git
  Cloning https://github.com/ariaghora/mpstemmer.git to /tmp/pip-req-build-kfa49jyv
  Running command git clone --filter=blob:none --quiet https://github.com/ariaghora/mpstemmer.git /tmp/pip-req-build-kfa49jyv
  Resolved https://github.com/ariaghora/mpstemmer.git to commit 25a5fd923af163a7eac3a5ec976984156ca8fa8b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Levenshtein in /usr/local/lib/python3.13/dist-packages (0.27.5)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.13/dist-packages (from Levenshtein) (3.14.6)

In [7]:
import string
from nltk.corpus import stopwords
from mpstemmer import MPStemmer

stemmer = MPStemmer()
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [9]:
def remove_html(text):
  html_pattern = re.compile('<.*?>')
  return html_pattern.sub(r'', text)

df['rm_html'] = df['text'].apply(remove_html)
df[['text', 'rm_html']].head()

                                                text                                            rm_html
0                                        Cek, promo,                                        Cek, promo,
1  Orang kaya bilek,&quot;anjir daging premium pa...  Orang kaya bilek,&quot;anjir daging premium pa...
2  Cara iris bawang nya aja masih bingung dan lam...  Cara iris bawang nya aja masih bingung dan lam...
3                       Did he just said bismillah??                       Did he just said bismillah??
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [10]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

df['rm_html'] = df['text'].apply(remove_html)

df[['text', 'rm_html']].head()

                                                text                                            rm_html
0                                        Cek, promo,                                        Cek, promo,
1  Orang kaya bilek,&quot;anjir daging premium pa...  Orang kaya bilek,&quot;anjir daging premium pa...
2  Cara iris bawang nya aja masih bingung dan lam...  Cara iris bawang nya aja masih bingung dan lam...
3                       Did he just said bismillah??                       Did he just said bismillah??
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [11]:
def remove_hashtag(text):
    return re.sub(r'#\w+', '', text)

df['rm_hashtag'] = df['rm_html'].apply(remove_hashtag)

df[['rm_html', 'rm_hashtag']].head()

                                             rm_html                                         rm_hashtag
0                                        Cek, promo,                                        Cek, promo,
1  Orang kaya bilek,&quot;anjir daging premium pa...  Orang kaya bilek,&quot;anjir daging premium pa...
2  Cara iris bawang nya aja masih bingung dan lam...  Cara iris bawang nya aja masih bingung dan lam...
3                       Did he just said bismillah??                       Did he just said bismillah??
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [12]:
df['lower_case'] = df['rm_hashtag'].str.lower()

df[['rm_hashtag', 'lower_case']].head()

                                          rm_hashtag                                         lower_case
0                                        Cek, promo,                                        cek, promo,
1  Orang kaya bilek,&quot;anjir daging premium pa...  orang kaya bilek,&quot;anjir daging premium pa...
2  Cara iris bawang nya aja masih bingung dan lam...  cara iris bawang nya aja masih bingung dan lam...
3                       Did he just said bismillah??                       did he just said bismillah??
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [13]:
def remove_rls(text):
    text = re.sub(r'https?://\S+', '', str(text))
    text = re.sub(r'http\S+', '', str(text))
    text = re.sub(r'www\S+', '', str(text))
    text = re.sub(r'\S+@\S+', '', str(text))
    return text

df['rm_url'] = df['lower_case'].apply(remove_rls)

df[['lower_case', 'rm_url']].head()

                                          lower_case                                             rm_url
0                                        cek, promo,                                        cek, promo,
1  orang kaya bilek,&quot;anjir daging premium pa...  orang kaya bilek,&quot;anjir daging premium pa...
2  cara iris bawang nya aja masih bingung dan lam...  cara iris bawang nya aja masih bingung dan lam...
3                       did he just said bismillah??                       did he just said bismillah??
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [14]:
def remove_punctuation_list(text):

    # Remove emoticon
    text = re.sub(r'(:\)|:-\)|:D|:-D|;\)|;-\))', '', text)
    text = re.sub(r'(:\(|:-\()', '', text)
    text = re.sub(r'(:v|:-v)', '', text)

    # Remove punctuation
    text = re.sub(r'[!"#$%&\'()*+,\-./:;<=>?@\[\]^_`{|}~]', ' ', text)

    # Rapikan spasi
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df['rm_punc'] = df['rm_url'].apply(remove_punctuation_list)

df[['rm_url', 'rm_punc']].head()

                                              rm_url                                            rm_punc
0                                        cek, promo,                                          cek promo
1  orang kaya bilek,&quot;anjir daging premium pa...  orang kaya bilek quot anjir daging premium pak...
2  cara iris bawang nya aja masih bingung dan lam...  cara iris bawang nya aja masih bingung dan lam...
3                       did he just said bismillah??                         did he just said bismillah
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [15]:
df['stem'] = df['rm_punc'].apply(
    lambda x: stemmer.stem_kalimat(x) if isinstance(x, str) else ''
)

df[['rm_punc', 'stem']].head()

                                             rm_punc                                               stem
0                                          cek promo                                          cek promo
1  orang kaya bilek quot anjir daging premium pak...  orang kaya bilek quot anjir daging premium pak...
2  cara iris bawang nya aja masih bingung dan lam...  cara iris bawang nya aja masih bingung dan lam...
3                         did he just said bismillah                         did he just said bismillah
4                                sekitar 15 biji aja                                sekitar 15 biji aja

In [16]:
sw = set(stopwords.words('indonesian'))

def remove_stopwords(text):
    return " ".join(
        [word for word in str(text).split() if word not in sw]
    )

df['rm_stopwords'] = df['stem'].apply(remove_stopwords)

df[['stem', 'rm_stopwords']].head()

                                                stem                                       rm_stopwords
0                                          cek promo                                          cek promo
1  orang kaya bilek quot anjir daging premium pak...  orang kaya bilek quot anjir daging premium pak...
2  cara iris bawang nya aja masih bingung dan lam...  iris bawang nya aja bingung lagak nya udah kay...
3                         did he just said bismillah                         did he just said bismillah
4                                sekitar 15 biji aja                                        15 biji aja

In [17]:
df["prepro"] = df['rm_stopwords']

In [18]:
df[["text", "prepro"]].head(1000)

                                                 text                                             prepro
0                                         Cek, promo,                                          cek promo
1   Orang kaya bilek,&quot;anjir daging premium pa...  orang kaya bilek quot anjir daging premium pak...
2   Cara iris bawang nya aja masih bingung dan lam...  iris bawang nya aja bingung lagak nya udah kay...
3                        Did he just said bismillah??                         did he just said bismillah
4                                 sekitar 15 biji aja                                        15 biji aja
..                                                ...                                                ...
95                              yang nonton 2025<br>👇                                       tonton 2025👇
96                       Bukannya bini nya Islam ya??                                 bini nya islam iya
97    bismillah ada rejeki buat makan ini yaallaaaaah                 bismillah rejeki makan yaallaaaaah
98  Bagus video nya tapi ngomong nya terlalu bnyak...  bagus video nya omong nya bnyak bagus nya maka...
99                               Islam kok makan babi                                   islam makan babi

[100 rows x 2 columns]

In [19]:
df.to_csv(
    "Hasil_preprocessing.csv",
    index=False,
    encoding="utf-8-sig"
)