<a href="https://colab.research.google.com/github/raflialdiansyah046-bot/Tugas_text_processing_comment_youtube/blob/main/tugas_text_processing_raditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pre processing

In [1]:
import requests
import json
import pandas as pd
import re
import nltk

In [2]:
api_key = "apa yah key nya"

video_id = "rR0A9xZlXqQ"
max_result = 100

url = f"https://www.googleapis.com/youtube/v3/commentThreads"

params = {
    "part": "snippet",
    "videoId": video_id,
    "maxResults": max_result,
    "key": api_key
}

response = requests.get(url, params=params)

print(response.status_code)

data = response.json()

200

In [3]:
comments = []

for item in data["items"]:
    comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
    comments.append(comment)

print("Jumlah komentar:", len(comments))

for comment in comments[:1000]:
    print(comment)

Jumlah komentar: 100
👍
Setara kalo makan sama bg nasinya 2liter😅
Selasa, 6 Oktober 2026 jam 13.46
Cek, promo,
Orang kaya bilek,&quot;anjir daging premium pake nasi
Cara iris bawang nya aja masih bingung dan lama tapi lagak nya udah kayak sef tapi kalau kamu itu sef tai nya anjing
Did he just said bismillah??
sekitar 15 biji aja
nyam nyam
Kok bisa ya? Lambungnya segede apa dia teh??
lanjut mang
😮
Assalamualaikum bang ,,,coba review daging unta utuh bang ...
itu daging sapi bang?
Babah
Jujur bang, w kira daging b2 sekilas
aku nak satu
Banf makan salmon 1 ton
Makan banyak tapi yg besar hanya bibir
Kelihatanya seperti dagin Baby
Where  you  come  from ?  And what your  mission above  study ?  Thank  you  guys .
Selamat Malam Saya Yayuk  mengajukan pertanyaan , Bagaimanakah mempertahankan daging supaya  tahan lama dan aman ?<br>Saya semoga pertanyaan ini dapat di terima dan di pahami .  Terima  Kasih .
Itu daging B2 bukan sapi.. keliatan banget waktu di asapin lemak nya dan antara daging ketutup lemaknya b2itu😂
<a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=714">11:54</a>
Bang tolong bibir potong dikit
dari tahun 2021 nonton tahun pas 2026😂
Astaghfirullah ini mah bukan daging sapi tapi babi kan
wah
P
geli banget ngeliat bawang nya
DAGING BABI YA BG<br>KARENA KAYAK SAMA DAGING BABI DARI KAMPUNG SAYA <br>SOALNYA SAYA ORANG KRISTEN<br>DAN SAYA UDAH PERNA COBA
Gw k
P
Ngiler sambel nya😢
babi emang ok
gue terakhir
🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩🥩
Enak nya bang
Close dulu
kecubunggggg
Kasih baking soda biar ijo
Boy.. kapan kapan buat konten makan daging terenak didunia yi  daging Babi.
Yang nonton 2026.?
Apkah anda Islam
Abang ini sukses bikin kita lapar
3.43 kaget jir😂😂😂
Yah gw doang yg nonton 2026
Mirip daging babi
Tak kira tadi B2<br>Sempet dikit baca judulnya
coba pork belly bang bara
SELALU
Kalo pengasapannya jelek gimana bang <a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=1074">17:54</a>
sesekali kalian makan daging babi biar tau gmn rasa daging terenak dimukanbumi yakali orang lain masa membvvnhh berani, perkaos berani, koruppppsi berani, melakukan dosal lain berani yang fi takuti cuma daging babi kan aneh,,,,
<a href="https://www.youtube.com/watch?v=rR0A9xZlXqQ&amp;t=698">11:38</a>
kayak daging babi
Kota Medan hadir selalu untuk mu mas bara😅😊
Mantap bang
Bang ... Masuk idul Adha buat Tema MAKAN DAGING UNTA Donk ....
Aku kasik nonton pada orang2 miskin Dan anak2 yg sudah Dan ustaz...  Mereka senang sekali ada orang kaya Gini..
Siapa yang nonton 2026
Yang sehat ya bang
itu daging apa bg
Itu daging B2 kalau GK salah
habis lebaran 2026 ada gk yang nonton tanboy kun kalo ada 😅ya
Daging bagian bawah perut
Ini daging apa ya
<b>habis lebaran 2026 ada gk yang nonton tanboy kun ,kalo ada</b> 😅<br>👇
Jadi laper😅
nnton pas lg puasa 2026.. jam 09.51,, enak bgt liat daging asap ni😥😅😅
.
nonton ini jam 1 siang hari puasa
bang gua bisa makan nasi tanpa kunyah
Jadi pengen buka jam 1
Bang lu Islam apa katolik?
No more &#39;Don&#39;t skip—this will change your life&#39; guilt-trip ads - all thanks to Blockify
Nonton sambil nunggu buka puasa
nonton pas puasa 2026 absenn dong
info yang nonton pas otw puasa 2026😂
Yg nonton puasa 2026
hadir
2026 ada?
Yummy 😋
2026 bg
go veg-
2026🗿🗿
Itu nama dagingnya apa bang tanboy?
Itu daging babi
67!
Mati lu makan kecubung
❤❤🎉
Kerja dimana tamboy meke liliput terus lu emang enak pah itu di bau banget juga lu ..
2026
Siapa yang nonton 2026 preennn😂
Lah gw sendiri yg nonton 2026😂
gua orang pertama yg nonton di 2026.
Gua jugs bsng baru nonton ini
AMAZING!
Gak sangkut digigi😂😂😂
yang nonton 2025<br>👇
Bukannya bini nya Islam ya??

In [4]:
df = pd.DataFrame({
    "text": comments
})

df.head()

                                                text
0                                                  👍
1          Setara kalo makan sama bg nasinya 2liter😅
2                   Selasa, 6 Oktober 2026 jam 13.46
3                                        Cek, promo,
4  Orang kaya bilek,&quot;anjir daging premium pa...

In [5]:
!pip install --upgrade git+https://github.com/ariaghora/mpstemmer.git
!pip install Levenshtein

Collecting git+https://github.com/ariaghora/mpstemmer.git
  Cloning https://github.com/ariaghora/mpstemmer.git to /tmp/pip-req-build-n2e87jef
  Running command git clone --filter=blob:none --quiet https://github.com/ariaghora/mpstemmer.git /tmp/pip-req-build-n2e87jef
  Resolved https://github.com/ariaghora/mpstemmer.git to commit 25a5fd923af163a7eac3a5ec976984156ca8fa8b
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mpstemmer
  Building wheel for mpstemmer (setup.py) ... done
  Created wheel for mpstemmer: filename=mpstemmer-0.1.0-py3-none-any.whl size=99832 sha256=b0beed320107e94a4d36a4a4fafe203c4fbe7fbb53b63d768503d52997892bff
  Stored in directory: /tmp/pip-ephem-wheel-cache-r823iia0/wheels/d0/b9/fd/dba0c7d44e5338db51da6ffcbe96db4326db3996a403f5ced1
Successfully built mpstemmer
Installing collected packages: mpstemmer
Successfully installed mpstemmer-0.1.0
Collecting Levenshtein
  Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (157 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.4/157.4 kB 3.9 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 49.6 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein
Successfully installed Levenshtein-0.27.5 rapidfuzz-3.14.6

In [6]:
import string
from nltk.corpus import stopwords
from mpstemmer import MPStemmer

stemmer = MPStemmer()
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
def remove_html(text):
  html_pattern = re.compile('<.*?>')
  return html_pattern.sub(r'', text)

df['rm_html'] = df['text'].apply(remove_html)
df[['text', 'rm_html']].head()

,text,rm_html
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,Setara kalo makan sama bg nasinya 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46","Selasa, 6 Oktober 2026 jam 13.46"
3,"Cek, promo,","Cek, promo,"
4,"Orang kaya bilek,&quot;anjir daging premium pa...","Orang kaya bilek,&quot;anjir daging premium pa..."

In [8]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

df['rm_html'] = df['text'].apply(remove_html)

df[['text', 'rm_html']].head()

,text,rm_html
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,Setara kalo makan sama bg nasinya 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46","Selasa, 6 Oktober 2026 jam 13.46"
3,"Cek, promo,","Cek, promo,"
4,"Orang kaya bilek,&quot;anjir daging premium pa...","Orang kaya bilek,&quot;anjir daging premium pa..."

In [9]:
def remove_hashtag(text):
    return re.sub(r'#\w+', '', text)

df['rm_hashtag'] = df['rm_html'].apply(remove_hashtag)

df[['rm_html', 'rm_hashtag']].head()

,rm_html,rm_hashtag
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,Setara kalo makan sama bg nasinya 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46","Selasa, 6 Oktober 2026 jam 13.46"
3,"Cek, promo,","Cek, promo,"
4,"Orang kaya bilek,&quot;anjir daging premium pa...","Orang kaya bilek,&quot;anjir daging premium pa..."

In [10]:
df['lower_case'] = df['rm_hashtag'].str.lower()

df[['rm_hashtag', 'lower_case']].head()

,rm_hashtag,lower_case
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,setara kalo makan sama bg nasinya 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46","selasa, 6 oktober 2026 jam 13.46"
3,"Cek, promo,","cek, promo,"
4,"Orang kaya bilek,&quot;anjir daging premium pa...","orang kaya bilek,&quot;anjir daging premium pa..."

In [11]:
def remove_rls(text):
    text = re.sub(r'https?://\S+', '', str(text))
    text = re.sub(r'http\S+', '', str(text))
    text = re.sub(r'www\S+', '', str(text))
    text = re.sub(r'\S+@\S+', '', str(text))
    return text

df['rm_url'] = df['lower_case'].apply(remove_rls)

df[['lower_case', 'rm_url']].head()

,lower_case,rm_url
0,👍,👍
1,setara kalo makan sama bg nasinya 2liter😅,setara kalo makan sama bg nasinya 2liter😅
2,"selasa, 6 oktober 2026 jam 13.46","selasa, 6 oktober 2026 jam 13.46"
3,"cek, promo,","cek, promo,"
4,"orang kaya bilek,&quot;anjir daging premium pa...","orang kaya bilek,&quot;anjir daging premium pa..."

In [12]:
def remove_punctuation_list(text):

    # Remove emoticon
    text = re.sub(r'(:\)|:-\)|:D|:-D|;\)|;-\))', '', text)
    text = re.sub(r'(:\(|:-\()', '', text)
    text = re.sub(r'(:v|:-v)', '', text)

    # Remove punctuation
    text = re.sub(r'[!"#$%&\'()*+,\-./:;<=>?@\[\]^_`{|}~]', ' ', text)

    # Rapikan spasi
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df['rm_punc'] = df['rm_url'].apply(remove_punctuation_list)

df[['rm_url', 'rm_punc']].head()

,rm_url,rm_punc
0,👍,👍
1,setara kalo makan sama bg nasinya 2liter😅,setara kalo makan sama bg nasinya 2liter😅
2,"selasa, 6 oktober 2026 jam 13.46",selasa 6 oktober 2026 jam 13 46
3,"cek, promo,",cek promo
4,"orang kaya bilek,&quot;anjir daging premium pa...",orang kaya bilek quot anjir daging premium pak...

In [13]:
df['stem'] = df['rm_punc'].apply(
    lambda x: stemmer.stem_kalimat(x) if isinstance(x, str) else ''
)

df[['rm_punc', 'stem']].head()

,rm_punc,stem
0,👍,👍
1,setara kalo makan sama bg nasinya 2liter😅,setara kalau makan sama bg nasi 2liter😅
2,selasa 6 oktober 2026 jam 13 46,selasa 6 oktober 2026 jam 13 46
3,cek promo,cek promo
4,orang kaya bilek quot anjir daging premium pak...,orang kaya bilek quot anjir daging premium pak...

In [14]:
sw = set(stopwords.words('indonesian'))

def remove_stopwords(text):
    return " ".join(
        [word for word in str(text).split() if word not in sw]
    )

df['rm_stopwords'] = df['stem'].apply(remove_stopwords)

df[['stem', 'rm_stopwords']].head()

,stem,rm_stopwords
0,👍,👍
1,setara kalau makan sama bg nasi 2liter😅,setara makan bg nasi 2liter😅
2,selasa 6 oktober 2026 jam 13 46,selasa 6 oktober 2026 jam 13 46
3,cek promo,cek promo
4,orang kaya bilek quot anjir daging premium pak...,orang kaya bilek quot anjir daging premium pak...

In [15]:
df["prepro"] = df['rm_stopwords']

In [16]:
df[["text", "prepro"]].head(1000)

,text,prepro
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,setara makan bg nasi 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46",selasa 6 oktober 2026 jam 13 46
3,"Cek, promo,",cek promo
4,"Orang kaya bilek,&quot;anjir daging premium pa...",orang kaya bilek quot anjir daging premium pak...
...,...,...
95,Gua jugs bsng baru nonton ini,gue jugs bsng tonton
96,AMAZING!,amazing
97,Gak sangkut digigi😂😂😂,sangkut digigi😂😂😂
98,yang nonton 2025<br>👇,tonton 2025👇
99,Bukannya bini nya Islam ya??,bini nya islam iya

In [17]:
df.to_csv(
    "Hasil_preprocessing.csv",
    index=False,
    encoding="utf-8-sig"
)

feature engineering

In [18]:
!pip -q install gensim
!pip -q install umap-learn plotly

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 73.8 MB/s eta 0:00:00

In [30]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk import word_tokenize
from gensim.models import Word2Vec
from gensim.models import FastText
from umap import UMAP
import plotly.express as px

In [21]:
df_fe = df[['text', 'prepro']].copy()

df_fe['prepro'] = df_fe['prepro'].fillna('').astype(str).str.strip()
df_fe = df_fe[df_fe['prepro'] != ''].reset_index(drop=True)

df_pre = df_fe['prepro']

print("Jumlah komentar:", len(df_pre))
df_fe[['text', 'prepro']].head()

Jumlah komentar: 97

,text,prepro
0,👍,👍
1,Setara kalo makan sama bg nasinya 2liter😅,setara makan bg nasi 2liter😅
2,"Selasa, 6 Oktober 2026 jam 13.46",selasa 6 oktober 2026 jam 13 46
3,"Cek, promo,",cek promo
4,"Orang kaya bilek,&quot;anjir daging premium pa...",orang kaya bilek quot anjir daging premium pak...

In [31]:
vectorizer_binary = CountVectorizer(binary=True)

X_binary = vectorizer_binary.fit_transform(df_pre)

df_onehot = pd.DataFrame(
    X_binary.toarray(),
    columns=vectorizer_binary.get_feature_names_out()
)

print("Ukuran matriks:", X_binary.shape)
display(df_onehot.iloc[:5, :15])

Ukuran matriks: (97, 238)

   09  11  13  15  17  2021  2025  2026  2liter  38  43  46  51  54  67
0   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0
1   0   0   0   0   0     0     0     0       1   0   0   0   0   0   0
2   0   0   1   0   0     0     0     1       0   0   0   1   0   0   0
3   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0
4   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0

In [32]:
vectorizer_count = CountVectorizer()

X_count = vectorizer_count.fit_transform(df_pre)

df_count = pd.DataFrame(
    X_count.toarray(),
    columns=vectorizer_count.get_feature_names_out()
)

print("Ukuran matriks:", X_count.shape)
display(df_count.iloc[:5, :15])

Ukuran matriks: (97, 238)

   09  11  13  15  17  2021  2025  2026  2liter  38  43  46  51  54  67
0   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0
1   0   0   0   0   0     0     0     0       1   0   0   0   0   0   0
2   0   0   1   0   0     0     0     1       0   0   0   1   0   0   0
3   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0
4   0   0   0   0   0     0     0     0       0   0   0   0   0   0   0

In [33]:
vectorizer_tfidf = TfidfVectorizer()

X_tfidf = vectorizer_tfidf.fit_transform(df_pre)

df_tfidf = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer_tfidf.get_feature_names_out()
)

print("Ukuran matriks:", X_tfidf.shape)
display(df_tfidf.iloc[:5, :15])

Ukuran matriks: (97, 238)

,09,11,13,15,17,2021,2025,2026,2liter,38,43,46,51,54,67
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.502965,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.449383,0.0,0.0,0.0,0.0,0.24257,0.000000,0.0,0.0,0.449383,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0

In [25]:
nltk.download('punkt')
nltk.download('punkt_tab')

sentences = [
    word_tokenize(tweet.lower())
    for tweet in df_pre
]

model_w2v = Word2Vec(
    sentences,
    min_count=1,
    vector_size=100,
    window=5,
    sg=0,
    epochs=10
)

print("10 kata pertama:")
print(model_w2v.wv.index_to_key[:10])

print("Ukuran vektor kata:", model_w2v.wv.vectors.shape)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

10 kata pertama:
['daging', 'tonton', 'bang', '2026', 'babi', 'gue', 'makan', 'nya', 'puasa', 'enak']
Ukuran vektor kata: (253, 100)

In [34]:
def get_document_vector(tokens, model):
    valid_vectors = [
        model.wv[word]
        for word in tokens
        if word in model.wv
    ]

    if len(valid_vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(valid_vectors, axis=0)


X_w2v = np.array([
    get_document_vector(doc, model_w2v)
    for doc in sentences
])

df_w2v = pd.DataFrame(
    X_w2v,
    columns=[f'w2v_{i+1}' for i in range(100)]
)

print("Ukuran fitur dokumen:", df_w2v.shape)
display(df_w2v.head())

Ukuran fitur dokumen: (97, 100)

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100
0,0.000711,0.008061,-0.004779,-0.000714,-0.004616,0.009568,0.009930,0.009652,-0.004366,-0.002345,...,-0.000267,0.007943,0.003325,0.008931,-0.004237,-0.003899,0.004603,0.001049,0.002847,-0.009231
1,0.006286,0.001812,-0.001806,0.002063,0.003198,0.000756,0.006743,-0.000625,0.001492,0.004467,...,0.000155,0.003043,-0.002798,-0.002933,0.000344,0.003323,0.001125,-0.002553,-0.002684,0.004559
2,0.000129,0.000814,0.002797,-0.003510,0.002176,0.000208,-0.000068,0.004582,-0.004849,-0.001816,...,-0.000205,0.000175,0.000263,0.002226,-0.001065,0.003075,-0.001477,-0.002935,-0.004162,-0.002328
3,-0.001792,0.007858,0.005955,-0.000628,0.008574,-0.005880,0.001419,0.006563,-0.002364,0.000700,...,-0.003524,-0.006558,0.004124,-0.009138,0.007532,0.005259,-0.002666,-0.002200,0.007833,0.001302
4,-0.001524,0.003728,-0.000252,0.003107,-0.000182,-0.000846,0.003631,-0.000817,-0.000883,0.000061,...,0.001676,0.002075,0.000732,-0.000954,0.003030,0.002398,0.001685,0.001640,0.000255,-0.000107

In [27]:
model_fasttext = FastText(
    sentences,
    min_count=1,
    vector_size=100,
    window=5,
    min_n=3,
    max_n=6,
    sg=1,
    epochs=10
)

print("10 kata pertama:")
print(model_fasttext.wv.index_to_key[:10])

print("Ukuran vektor kata:", model_fasttext.wv.vectors.shape)

10 kata pertama:
['daging', 'tonton', 'bang', '2026', 'babi', 'gue', 'makan', 'nya', 'puasa', 'enak']
Ukuran vektor kata: (253, 100)

In [35]:
X_fasttext = np.array([
    get_document_vector(doc, model_fasttext)
    for doc in sentences
])

df_fasttext = pd.DataFrame(
    X_fasttext,
    columns=[f'fasttext_{i+1}' for i in range(100)]
)

print("Ukuran fitur dokumen:", df_fasttext.shape)
display(df_fasttext.head())

Ukuran fitur dokumen: (97, 100)

,fasttext_1,fasttext_2,fasttext_3,fasttext_4,fasttext_5,fasttext_6,fasttext_7,fasttext_8,fasttext_9,fasttext_10,...,fasttext_91,fasttext_92,fasttext_93,fasttext_94,fasttext_95,fasttext_96,fasttext_97,fasttext_98,fasttext_99,fasttext_100
0,-0.003824,0.008684,-0.001141,-0.004442,-0.005341,0.004981,0.006717,0.001267,0.001403,-0.004289,...,-0.005105,0.008850,0.005094,0.009353,-0.005305,-0.004399,-0.001669,0.002918,0.003094,-0.004734
1,0.000843,-0.000102,-0.000913,0.000290,0.000541,-0.000557,0.001652,-0.000203,0.001783,0.001570,...,-0.000753,-0.000543,0.000344,-0.000025,-0.000966,0.001403,0.000845,-0.000566,-0.000943,0.001031
2,-0.000407,0.000688,0.000187,0.001428,0.003475,-0.001112,0.000010,0.001090,-0.001694,0.001531,...,-0.000142,-0.000821,0.000615,0.001173,-0.001747,0.001467,-0.001403,0.000420,-0.000067,0.000532
3,0.000470,0.001317,-0.000690,0.002432,0.002702,-0.002003,0.001196,0.000853,-0.000691,0.001164,...,0.000766,-0.000824,0.000143,-0.000856,-0.001614,0.000126,0.000416,0.001557,0.000823,-0.000079
4,-0.000533,-0.000394,-0.001376,0.000201,0.001179,0.000394,0.000429,-0.001166,0.000083,0.001017,...,0.000629,0.000784,0.000174,-0.000359,0.000092,0.001335,-0.000030,0.001389,-0.000958,0.000421

In [36]:
def visualisasi_embedding(model, judul):
    vectors = model.wv.vectors
    words = model.wv.index_to_key

    if len(words) < 3:
        print("Kosakata terlalu sedikit untuk visualisasi UMAP.")
        return

    reducer = UMAP(
        n_components=2,
        n_neighbors=min(15, len(words) - 1),
        random_state=42
    )

    coordinates = reducer.fit_transform(vectors)

    df_plot = pd.DataFrame(
        coordinates,
        columns=['umap1', 'umap2']
    )

    df_plot['word'] = words

    fig = px.scatter(
        df_plot,
        x='umap1',
        y='umap2',
        text='word',
        title=judul
    )

    fig.update_traces(textposition='top center')
    fig.show()


visualisasi_embedding(model_w2v, 'Word2Vec Visualization')

visualisasi_embedding(model_fasttext, 'FastText Visualization')

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

In [38]:
df_onehot.to_csv('features_onehot.csv', index=False)
df_count.to_csv('features_count.csv', index=False)
df_tfidf.to_csv('features_tfidf.csv', index=False)
df_w2v.to_csv('features_word2vec.csv', index=False)
df_fasttext.to_csv('features_fasttext.csv', index=False)

print("all done")

all done